Module6 task1
htmlacademy-yii/330197-task-force-1 pull request #11
Opened 2020-06-29 19:22 UTC by Nika-Hanover

2020-07-06 21:19 UTC, Ovsyanka commented
Похоже, у тебя были какие-то проблемы с git, судя по коммитам с решением каких-то конфликтов. По идее, у тебя вообще не должно быть причин для возникновения конфликтов. Работа с гит - не тема курса, но, при желании можно это обсудить на консультации.

В следующий раз стоит действовать точно по инструкции, которая дается в начале каждого задания:

    В вашей локальной копии переключитесь в ветку master
    git checkout master
    Заберите изменения из репозитория Академии¹ (или academy)
    git pull academy master
    Отправьте изменения ветки master в ваш форк на Гитхабе (или origin)
    git push origin master
    Когда вы обновили master, создайте ветку для выполнения задания
    git checkout -b module6-task1

У тебя в ветку по заданию каким-то образом попал коммит 4b5d780a752c01d89e2aa0ee4bdb8c57ee8e04bc, который базируется на более старом мастере и в целом мне не понятно, что происходит в репозитории

![image](https://user-images.githubusercontent.com/1226722/86645000-4d5ff280-bfde-11ea-8ea4-b93cd30c1bf0.png)

2020-07-06 21:28 UTC, Ovsyanka commented on db_create.sql
> +CREATE DATABASE IF NOT EXISTS task_force;
IF NOT EXISTS ни тут, ни далее не нужно, ведь в рамках этого же скрипта БД удаляется и ее быть не должно, так же как и таблиц. И если по какой-то причине она есть - как раз очень было бы хорошо, если бы скрипт завершился с ошибкой, о том, что бд уже есть, так как эта ошибка покажет, что что-то пошло не так. Приведу пример: если бы ты допустила ошибку в инструкции удаления таблицы - ее легко можно не заметить, так как инструкции `CREATE DATABASE/TABLE IF NOT EXISTS ...` выполнятся без ошибок.

2020-07-06 21:32 UTC, Ovsyanka commented on db_create.sql
> +) AUTO_INCREMENT=9 DEFAULT CHARSET=UTF8;
Установка начального значения для авто-инкремента попала сюда, вероятно, по ошибке.

2020-07-06 21:35 UTC, Ovsyanka commented on db_create.sql
> +  KEY idcity (idcity),
Индексы для foreign key [создаются автоматически](https://stackoverflow.com/a/1145183/3653002), так что можно их отдельно не прописывать.

2020-07-06 21:37 UTC, Ovsyanka commented on db_create.sql
> +  file_3 varchar(255) DEFAULT NULL,
В ТЗ вроде-бы нету ограничения на кол-во файлов. Лучше хранить их в отдельной таблице - так с ними и работать проще будет.

2020-07-06 21:39 UTC, Ovsyanka commented on db_create.sql
> +  idcustomer mediumint(9) DEFAULT NULL,
У задания не может не быть автора. Он должен быть обязательно. Соовтетственно, тут нужно использовать not null. Это касается многих других полей, стоит их все проверить, я вижу, что у тебя почти везде по умолчанию null.

2020-07-06 23:00 UTC, Ovsyanka commented on db_migration - module6-task1.sql
> +/*Обновляем данные в таблтце tasks чтобы появились задачи без исполнителей. Для тестирования фильтра*/
В ТЗ написано:
> Разработка всего проекта ведётся исключительно на основе фреймворка Yii 2 и его стандартных компонент. Если что-либо (валидация, пагинация, шаблонизация и тому подобное возможно сделать средствами компонент фреймворка, то это должно быть сделано **этими средствами**. 

Так что если есть желание использовать миграции, нужно использовать [компонент миграций yii2](https://www.yiiframework.com/doc/guide/2.0/en/db-migrations).

Хотя, миграции для данных задач использовать не обязательно. Ты можешь изменить изначальную структуру БД и начальные данные. Миграции нужны для обновления (обычно боевого/продуктового/production) долгоживущего экземпляра приложения, когда нет возможности его грохнуть и создать заново. А в нашем случае это сделать можно и, более того, это должно быть максимально удобно для упрощения разработки и тестирования.

2020-07-06 23:11 UTC, Ovsyanka commented on frontend/controllers/TasksController.php
> +
Не надо отключать Csrf валидацию, это вещь [полезная](https://habr.com/ru/post/318748/)?

2020-07-06 23:57 UTC, Ovsyanka commented on frontend/controllers/TasksController.php
> +        $cats = $category->find()->select(['category', 'id'])->from('categories')->all();
Котики, это замечательно! Но мы тут категории получаем, а не котиков :Р

Создавать экземпляр Categories не нужно - это модель категории. У тебя вообще есть возможность ее создать только потому, что у нее нет обязательных полей. Если бы были - создать ее "пустой" не получилось бы. Вообще, в модели Categories стоит [указать](https://www.yiiframework.com/doc/guide/2.0/en/structure-models#validation-rules) в rules обязательные поля. Как мне кажется, оба поля должны быть обязательными - и category и icon.

Метод find статический, для его использования не надо создавать экземпляр. Можно переписать так:
`$categories = Categories::find()->select(['category', 'id'])->all();`

2020-07-06 23:59 UTC, Ovsyanka commented on frontend/controllers/TasksController.php
> +}
[Пустая строка в конце файла](https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file) требуется [PSR-12](https://www.php-fig.org/psr/psr-12/) (а ранее [PSR-2 (deprecated)](https://www.php-fig.org/psr/psr-2/)). [vscode settings](https://stackoverflow.com/questions/44704968/visual-studio-code-insert-new-line-at-the-end-of-files)

2020-07-07 00:01 UTC, Ovsyanka commented on frontend/controllers/TasksController.php
> +	if (Yii::$app->request->getIsPost()) {
А если это не пост запрос - выполнение продолжится с неопределенной переменной $form_data.

В тему, рекомендую почитать https://habr.com/ru/post/348074/

2020-07-07 00:04 UTC, Ovsyanka commented on frontend/views/site/tasks.php
>  /* @var $model \frontend\models\ContactForm */
В начале вьюхи стоит перечислять все используемые в ней параметры. У тебя они перечислены ,но не соответствуют действительности.

2020-07-07 00:05 UTC, Ovsyanka commented on frontend/views/site/tasks.php
> +// use yii\bootstrap\ActiveForm;
Не используемый код надо удалять (за редким исключением).

2020-07-07 00:06 UTC, Ovsyanka commented on frontend/views/site/tasks.php
> +                <?php if(isset($data)):?>
Нужно использовать осмысленные названия переменных (критерий Б2).

2020-07-07 00:26 UTC, Ovsyanka commented on frontend/controllers/TasksController.php
> +	}
Поехало форматирование. Из-за того, что перемешаны табы и пробелы в качестве отступов. Рекомендую настроить редактор, тчобы он использовал только один тип отступов. По критериям требуется PSR-2 (хотя он и deprecated), в нем требуются прорбелы.

2020-07-07 01:08 UTC, Ovsyanka commented on frontend/controllers/TasksController.php
> +    	$data['data'] = $task->getData($form_data);
TaskModule->getData выполняет слишком много всего (критерий Б6). В нем и парсинг данных формы фильтрации и выполнение запросов к БД и форматирование данных.

Стоит это все разделить.

А еще в самом задании написано:

    Создать модели для обоих форм;
    Заполнить модель нужными свойствами;
    Передать форму в представление и отрисовать все её элементы;
    Фильтровать список заданий по критериям из формы.

У тебя нет модели для формы поиска. Ее можно назвать TasksSearch и в ней создать метод search или find, в котором описать логику поиска заданий.

Более низкоуровневые запросы можно описать в классе TasksQuery. Рекомендую посмотреть [видео](https://www.youtube.com/watch?v=TyiSYxFL8Gg&feature=youtu.be&t=24m13s), там и на эту тему и на другие весьма полезная информация.

В шаблон передавать экземпляр TasksQuery, полученный из TasksSearch->search().

То же самое касается списка пользователей.

2020-07-07 01:11 UTC, Ovsyanka commented on frontend/models/CategoriesSearch.php
> +<?php
Этот класс нигде не используется, в репозитории не должно быть неиспользуемого кода. Исключение - если ты точно планируешь его использовать. А поиска категорий вроде, не планируется.

2020-07-07 01:15 UTC, Ovsyanka reviewed
html файлы следует удалить из предыдущего расположения. Не нужно их дублировать.

2020-07-07 01:21 UTC, Ovsyanka commented
Внешний вид стал ![гораздо лучше](https://user-images.githubusercontent.com/1226722/86682083-814c0f80-c000-11ea-9d67-38b8fa017037.png), но все еще не такой же как в html ![исходнике](https://user-images.githubusercontent.com/1226722/86682009-709b9980-c000-11ea-97ef-66a9e00a0637.png). Честно говоря, не знаю, насколько это важно, но по крайней мере то, что шапка с меню смещена уж очень просается в глаза. А рамки вокруг категорий и другие мелкие различия, вероятно, не имеют значения.

2020-07-07 01:31 UTC, Ovsyanka reviewed
Заметил, что у тебя есть файл categories.php - вероятно, он у тебя был изначально и ты его не корректно переименовала. Это надо было делать так: https://stackoverflow.com/questions/1793735/change-case-of-a-file-on-windows

Мне не охота тестировать на Windows, но, думаю, получится исправить это как-то так:
1. Переименовать Categories.php во что-нибудь.
2. git rm categories.php
3. git commit -m "Remove redundant categories.php"
4. Переименовать Categories.php обратно

2020-07-07 01:39 UTC, Ovsyanka commented
В целом, все очень даже неплохо! Есть еще над чем поработать, но то, что я без проблем смог поднять у себя инстанс приложения и функционал фильтрации работает - замечательный старт, а дальше уже можно заниматься доработкой и рефакторингом.

2020-07-08 17:46 UTC, Ovsyanka commented on db_migration - module6-task1.sql
> +/*Обновляем данные в таблтце tasks чтобы появились задачи без исполнителей. Для тестирования фильтра*/
Я ошибся насчет того, что миграции использовать не обязательно. Согласно критерию Б18 их использовать обязательно:
> Вся работа над структурой и заполнением БД (за исключением первоначальной схемы и дампов, созданных по заданию) ведётся только через миграции.

Но как минимум стоит разделить миграции структуры БД и заполнения данными - не стоит смешивать их в рамках одного файла миграции.

2020-07-11 17:13 UTC, Nika-Hanover commented on db_migration - module6-task1.sql
> +/*Обновляем данные в таблтце tasks чтобы появились задачи без исполнителей. Для тестирования фильтра*/
Хорошо, если использование миграций обязательны, то в дальнейшем буду их использовать. Сейчас я исправила замечания по созданию и наполнению базы данных как оно должно быть. Дальше буду вносить правки только через миграции, потому что сейчас я уже не помню точно на каком этапе я что меняла.

2020-09-30 17:54 UTC, Nika-Hanover commented on frontend/controllers/TasksController.php
> +    	$data['data'] = $task->getData($form_data);
На этом пункте я зашла в тупик. И сейчас я не уверена, что правильно поняла что я здесь должна исправить и как оно в результате должно выглядеть. Мне раньше не приходилось создавать так много моделей и методов для решения задачи, которая по сути выполняется одним запросом в бд.

2020-10-05 00:44 UTC, Ovsyanka commented on db_migration - module6-task1.sql
> +/*Обновляем данные в таблтце tasks чтобы появились задачи без исполнителей. Для тестирования фильтра*/
sql запросы, которые уже есть хорошо бы привести в порядок.

Б14: "В коде проекта не должно быть **файлов** и частей кода, **которые не используются**, включая, закомментированные участки кода, неиспользуемые функции и переменные."

Файл `db_v_module5-task2` для чего-то используется? Если нет - его надо удалить. Если он используется - стоит переименовать его так, чтобы было понятно, что это создание базы данных. Например db_create_alternative.sql.

`db_migration - module6-task1` - это стоит либо оформить в виде yii2 миграции, как я писал ранее, либо удалить. Текущая версия скрипта не работает на БД, созданной скриптом db_inserts.sql из-за обновленной структуры БД. Если по миграциям есть вопросы, можем поговорить в рамках консультации.

Скрипты по созданию (db_create) и начальному заполнению (db_inserts) БД данными нужно оставить и после принятия данного пулл-реквеста редактировать их больше не надо.

Я еще рекомендую добавить в db_inserts.sql `USE task_force;` в начало. Так удобнее выполнять скрипт. Если там этого нет - нужно перед выполнением скрипта узнать имя БД и добавить его в команду. И получается, что запуск этого скрипта отличается от запуска скрипта создания БД, что не интуитивно. Пример, как это выглядит у меня:
```
docker-compose exec -T mysql mysql < db_create.sql
docker-compose exec -T mysql mysql task_force < db_inserts.sql
```

2020-10-05 00:49 UTC, Ovsyanka commented on frontend/controllers/UsersController.php
>      }
"Лишний" код. Он включает CSRF, которая и так включена. Зачем?

2020-10-05 00:56 UTC, Ovsyanka commented on frontend/controllers/TasksController.php
> +    }
Нужно исправить отступ.

2020-10-05 01:40 UTC, Ovsyanka commented on db_create.sql
>  ) DEFAULT CHARSET=utf8;
[Стоит](https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file) в конце текстовых файлов оставлять переход строки. Рекомендую настроить редактор соответствующим образом, чтобы он делал это автоматически.

2020-10-05 03:15 UTC, Ovsyanka commented on frontend/controllers/TasksController.php
> +        return $this->render('/site/tasks', $data);
Да, тут ты намудрила =) По заданию требовалось создать модель формы поиска, а вот модуль создавать не требовалось.

Опишу вкратце как должно быть, если будут сложности - можно будет обсудить в рамках консультации.

Модель формы поиска - это класс, в котором описаны поля этой формы и который позволяет создать запрос на выборку к БД в соответствии со значениями этих полей.

[Тут](https://www.yiiframework.com/doc/guide/2.0/en/structure-models) можно почитать про модели форм. А [тут](https://www.yiiframework.com/doc/guide/2.0/en/input-forms) написано как использовать такие модели во вью. [Тут](https://www.yiiframework.com/doc/guide/2.0/en/input-validation) про валидацию пользовательского ввода.

То есть тут (в контроллере) она должна использоваться примерно так:

```
$tasksSearchForm = new TasksSearchForm();

// Заполняем модель формы данными пользователя.
$tasksSearchForm->load($form_data);

// Проверка корректности заполнения полей, 
$tasksSearchForm->validate();

// Получаем DataProvider с задачами отобранными в соответствии с критериями.
$tasks = $tasksSearchForm->search(); //returns DataProviderInterface

// Передаем DataProvider во вьюху, а в ней уже описываем как это все отображать.
return $this->render('/site/tasks', $tasks);
```

2020-10-05 03:18 UTC, Ovsyanka commented on frontend/views/site/users.php
> +/* @var $addition \frontend\controllers\UsersController*/
Классы указаны не те.

2020-10-05 03:22 UTC, Ovsyanka requested changes
Во-первых хочу заметить, что фильтрация работает и это уже хорошая работа. К сожалению, сделано не тем методом, который описан в задании, так что нужно его еще раз внимательно прочитать и сделать как там написано - создать модели форм поиска и использовать ActiveQuery для фильтрации данных.

Еще нужно удостовериться, что после фильтрации фильтры не сбрасываются, как это происходит сейчас. Если сделать тем методом, что описан в задании с этим проблем не будет.

2020-10-05 16:12 UTC, Ovsyanka commented on frontend/controllers/TasksController.php
> +        return $this->render('/site/tasks', $data);
Сейчас заметил, что ранее я писал, что во вью можно передавать экземпляр TasksQuery, а не DataProvider. Можно и так и так. Просто TasksQuery может потом потребоваться заменить на DataProvider для реализации пагинации. В общем, тут делай как тебе больше нравится на данный момент.

2020-10-05 16:16 UTC, Ovsyanka commented on frontend/controllers/TasksController.php
> +        return $this->render('/site/tasks', $data);
Еще, изменения входных данных для вьюхи, естественным образом потребует и ее переработку. Например, внутри нее для получения данных нужно будет обращаться уже не к ассоциативному массиву, а к моделям.

Вместо `$task['description']` будет `$task->description` и т.п.

Я подумал, что стоит это явно отметить, чтобы тебя этот факт не смущал.

2020-10-06 16:56 UTC, Nika-Hanover commented on frontend/controllers/UsersController.php
>      }
Без этой части кода выпадает ошибка: 
"
Bad Request (#400)
Unable to verify your data submission.

The above error occurred while the Web server was processing your request.

Please contact us if you think this is a server error. Thank you.
"

2020-10-07 01:20 UTC, Ovsyanka commented on frontend/controllers/UsersController.php
>      }
Действительно, нужно сделать, чтобы csrf токен передавался в POST запросе. Поскольку ты формируешь форму "руками" тебе нужно [самой заботиться об этом](https://stackoverflow.com/a/30698340/3653002). Но вообще, среди критериев курса есть требование использовать средства фрейморка, когда это возможно (Б8. Нет велосипедов). В yii2 есть класс ActiveForm, который как раз предназначен для формирования форм. На мой взгляд это спорный вопрос - попадает ли формирование форм руками под этот критерий. Но я бы рекомендовал все-таки использовать ActiveForm хотя-бы потому, что это удобнее.

Так что это нужно [переписать](https://www.yiiframework.com/doc/guide/2.0/en/start-forms) на использование ActiveForm и тогда yii2 сам позаботится о том, чтобы добавить hidden input с csrf токеном.

2020-10-07 18:37 UTC, Nika-Hanover commented
Я переделала форму через ActiveForm, но у меня как и раньше не получается отправить форму. Я не знаю как это исправить.

2020-10-07 22:27 UTC, Ovsyanka commented
Это вопрос можно проработать на консультации.

2020-10-08 05:36 UTC, Nika-Hanover commented
Так я вернула просто старый код. Я с самого начала пыталась настроить форму через ActiveForm. Поскольку после отрисовки формы оказалось, что кнопка не работает и форма не отправляется я записплась на консультацию. В результате ты сказал, что это баг yii и не обязательно настраивать форму через ActiveForm. Поэтому я и сделала форму как умела.  Теперь оказывается нужно обязательно для форм использовать ActiveForm. Но вопрос с которым я обращалась вначале остался то же. Какой смысл тогда был от первой консультации? И сколько ещё мне нужно заказать консультаций чтобы решить эту одну единственную проблему?

2020-10-11 00:05 UTC, Ovsyanka commented
> Поскольку после отрисовки формы оказалось, что кнопка не работает и форма не отправляется я записплась на консультацию. В результате ты сказал, что это баг yii и не обязательно настраивать форму через ActiveForm.

Поскольку консультация была устная и довольно давно - я уже не помню деталей разговора, так что пока не могу это прокомментировать. Если тебе хочется в этот вопрос углубиться и разобраться с ним - напиши мне, пожалуйста, id коммита, актуального на момент первой консультации и опиши в чем заключался этот баг.

> Теперь оказывается нужно обязательно для форм использовать ActiveForm.

Смотри, я лишь указал на конкретный критерий проверки и написал как я его понимаю. Так же я написал:

> На мой взгляд это спорный вопрос - попадает ли формирование форм руками под этот критерий. Но я бы рекомендовал все-таки использовать ActiveForm хотя-бы потому, что это удобнее.

Во время первой консультации я, вероятно, придерживался мнения, что использование ActiveForm под этот критерий не попадает, так как в нем говорится о "функциях". А класс - это все-таки не функция. Но если рассматривать термин "функция" в более широком смысле, то тогда использование ActiveForm под это попадает.

Кроме того, не стоит забывать о том, что написать работающий код (формирование формы руками) и потом отрефакторить его (переписать ан использование ActiveForm) - лучше для обучения, чем сразу написать второй вариант, поскольку это дает тебе возможность ощутить сравнить их на собственном опыте и сформировать собственное мнение о преимуществах/недостатках подходов. В том числе поэтому я мог предложить тебе написать форму руками для начала.

> Какой смысл тогда был от первой консультации? И сколько ещё мне нужно заказать консультаций чтобы решить эту одну единственную проблему?

Смысл и цели консультации определяет ученик в первую очередь. Так что этот вопрос скорее к тебе. Я, честно говоря, не помню уже ее деталей.

> И сколько ещё мне нужно заказать консультаций чтобы решить эту одну единственную проблему?

Это зависит от тебя и от наставника и заранее никто не может ответить на этот вопрос. Ведь в консультации участвуют оба - наставник объясняет, а ученик воспринимает. И то, поймет ли ученик наставника зависит от их взаимодействия. Конкретно в данном случае, я думаю, одной получасовой консультации должно быть достаточно.

2020-10-11 00:37 UTC, Ovsyanka commented
Вообще, я вот стал смотреть логи телеграма и пока, честно говоря, не получается такого, чтобы я тебе сказал сделать без ActiveForm. После консультации прошло очень много времени и я вот помню ее очень смутно. Так что это нормально, что ты тоже, видимо, не очень хорошо ее запомнила.

Консультация у нас была проведена 29 июня (запись о звонке в Телеграм). 

В ЛК указана дата 7 июля, поскольку ты отправила заявку на консультацию уже после ее фактического проведения по моей просьбе:

> Чтобы не забыть - оставиь, плз, заявку на консультацию, которую мы провели - 30 мин, на любое время. Я ее просто отмечу проведенной. Будем считать, что в нее входит и текстовое общение до сих пор.

После этого касательно ActiveForm у нас был такой разговор:

> Привет. Отправила задание на проверку. Форму переделала без ActiveForm. Вроде бы все работает. Будет время проверь пожалуйста.

> Привет, хорошо, посмотрю на днях. Сразу вопрос - почему без ActiveForm? Если это обусловлено только тем, что с ActiveForm не получилось - есть ли желание с этим разобраться потом?

> Я поняла, что ActiveForm скорее всего удобнее пользоваться если идёт привязка формы к одной таблице, например для сохранения данных для регистрации или поиск только по полям одной таблицы. В других случаях с ней больше мороки чем пользы, потому что нужно делать много ручных правок и врезультате форма всё равно не будет выглядеть как хотелось бы. Это моё личное мнение, я могу ошибаться.

> Ага, хорошо. Спасибо за развернутый ответ. Пока не буду его никак комментировать, посмотрю код сначала

Видно, что после консультации для меня было неожиданностью то, что ты не использовала ActiveForm. Продолжение разговора:

> Т.е. как я поняла в нашем случае лучше всё-таки обходиться без ActiveForm?

> Не, как раз-таки ActiveForm будет уместна по идее =) Ты читала уже мое ревью? Там я [написал](https://github.com/htmlacademy-yii/330197-task-force-1/pull/11#discussion_r450556705) про модель для формы поиска.

В общем, похоже, что я все-таки изначально тебе советовал использовать ActiveForm и продолжаю это делать. И на первой консультации судя по нашему разговору после нее мы решили использовать ActiveForm, у тебя возникли с этим проблемы и мы предполагали провести вторую консультацию, чтобы их решить, но так ее и не провели.

В итоге из-за большого перерыва и из-за того, что мы оба поленились внимательно перечитать нашу прошлую переписку - ты подняла те же самые вопросы, что и раньше (по поводу модели формы поиска, например), а я заново на них ответил, немного иначе в деталях, но по сути так же как и в прошлый раз.

2020-10-30 23:51 UTC, Ovsyanka commented on console/migrations/m201022_173624_add_views_column_to_users_table.php
> +class m201022_173624_add_views_column_to_users_table extends Migration
С миграцией все замечательно. Но раз добавилась колонка в таблицу юзеров - стоит добавить соответствующее поле и в модель пользователя.

2020-10-30 23:56 UTC, Ovsyanka commented on frontend/controllers/TasksController.php
>      }
Нарушен отступ

2020-10-31 00:33 UTC, Ovsyanka commented on frontend/views/site/users.php
> +                                ], false)->label('',['class' => 'visually-hidden checkbox__input'])?>
Функция checkboxList принимает только два параметра, а false тут третий.

2020-10-31 00:45 UTC, Ovsyanka commented on frontend/controllers/UsersController.php
>          return $this->render('/site/users',$data);
Это не критично, но из соображений читаемости лучше все передаваемые параметры сгруппировать в одном месте, чтобы не надо было просматривать код всей функции, чтобы понять из чего состоит $data, например так:
```php
return $this->render('/site/users',[
'users' => $users,
'users_addition' => $users_addition,
...
]);
```

Можно поработать над передаваемыми параметрами, чтобы по названию было понятно, что в нем лежит. Например, sort - что там? Судя по коду, это поле, по которому осуществляется сортировка. Можно назвать sortField.
free, online, feedback, favorite - по названиям (мне) не понятно что там. По коду тоже не совсем понятно что это и для чего. Пытаюсь выяснить, как это используется - оказывается, что никак. Надо удалить.

model - хорошо бы отразить в названии модель чего.

2020-11-09 21:52 UTC, Ovsyanka reviewed
_Это сообщение я начал писать еще до твоего последнего коммита и сейчас, закрывая вкладки, заметил, что оно не отправлено. Так что если в последнем коммите что-то из этого уже исправлено - просто игнорируй_

Файлы php, info, echo добавлены, вероятно, по ошибке? Если да - надо их удалить, если нет - скажи, для чего они.

Первое нажатие на кнопку поиска на страницах Задание и Исполнители не работает. Для отправки формы требуется нажать на кнопку два раза. Надо поправить, чтобы кнопка работала с первого раза.

Опечатка в слове Feedback по всему проекту.

2020-12-11 14:59 UTC, merged